# Generated by Django 5.0.1 on 2024-02-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('tecnologia', models.CharField(max_length=50)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
